### PR TITLE
[16.0] component: Migration to 16.0

### PR DESCRIPTION
**Pull request by bizzappdev**

### CODE REVIEW

**Comment by bizzappdev** [comment]
Ready for the review.

**Comment by gurneyalex** [comment]
Can you include https://github.com/OCA/connector/pull/448 in this PR ?

**Comment by bizzappdev** [comment]
> Can you include #448 in this PR ?

Done.

**Comment by rven** [comment]
@bizzappdev You didn't follow the migration guidelines!

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#technical-method-to-migrate-a-module-from-150-to-160-branch

"version": "16.0.0.0.0", => "version": "16.0.1.0.0",

But you also changed the version number in the commit [IMP] component: black, isort, prettier, which is not as mentioned in the migration wiki.
IMP => MIG

**Comment by simahawk** [comment]
pls check https://github.com/OCA/connector/pull/441

**Pull request closed without merging**
