### PR TITLE
[10.0] [IMP] component_event

### PR DESCRIPTION
**Pull request by anand-serpentcs**
Component Event
=============

This will fix the issus and adds the condition, event should not be triggered before the registry has been loaded.

Backport PR #283 to v10.0

### CODE REVIEW

**Comment by guewen** [comment]
Thanks for the backport! If you tested #283 could you add a comment / approve it? It would help to get it merged.

**Comment by guewen** [comment]
It would be nice if you keep the original commit's description and authorship through a cherry-pick for instance.

**Comment by anand-serpentcs** [comment]
@guewen Sure I believe in preserving the main author commit revision, but now I have improved the code, as I see the test cases are failing in your PR. Can you please take a look at the code once.

**Comment by guewen** [comment]
@anand-serpentcs I forgot that my commit failed on travis :sob: Your commit looks good to me and of course you are the author of this one ;)

Could you update your commit message with something more descriptive so we can remember why it was added?

Suggestion:

```
component_event: do not raise events during install through UI

During install / upgrade of addons, the odoo registry is recreated and not
flagged as ready. At the end of the odoo registry loading, the registry
of components will be built. If we install component_event from the UI
(not with -i), the component's registry is already flagged as "ready",
but the 'base.event.collecter' component is not yet referenced in it.
```

Thanks :)

**Comment by anand-serpentcs** [comment]
@guewen I have improved the commit message, thanks for authoring me this commit  ;)

Also would you please +1 by the review, so we could merge this and fixup the original issue, thanks.

**Review by guewen — APPROVED** [review]
Thanks!

**Comment by martintorresvm** [comment]
@anand-serpentcs seems still small issue on Travis

**Comment by anand-serpentcs** [comment]
@victormartinelicocorp Those travis is failing in the v10 code itself. You could also check the other PR it is same issue, not from our code.

Rather from our code the test cases on the travis are fixed, which was failing earlier :)

**Review by serpentcs-dev1 — APPROVED** [review]
Tested in local, it resolves the issue! :+1:

**Comment by martintorresvm** [comment]
@anand-serpentcs At least we need to justify that Travis is not failing because of this module `component_event`.

```
************* Module component_event
component_event/README.rst:69: [E7901(rst-syntax-error), ]  Unexpected possible title overline or transition.|Treating it as ordinary text because it's so short.
************* Module component_event.tests.test_event
component_event/tests/test_event.py:13: [W7950(odoo-addons-relative-import), ] Same Odoo module absolute import. You should use relative import with "." instead of "openerp.addons.component_event"
component_event/tests/test_event.py:14: [W7950(odoo-addons-relative-import), ] Same Odoo module absolute import. You should use relative import with "." instead of "openerp.addons.component_event"
```

The Readme `Know issues` section is not necessary as we have none issue to report, please remove it, make sure that rst file is well construct.

**Comment by guewen** [comment]
I fixed the build here #295, please review it.
It should not be fixed here, but this PR can be rebased once #295 is merged.

**Comment by guewen** [comment]
You can now rebase your PR, thanks!

**Comment by anand-serpentcs** [comment]
@guewen Thanks Guewen, the travis is now green :+1: 

@victormartinelicocorp , Can we move ahead?

**Comment by martintorresvm** [comment]
@elicoidal Could you review?

**Review by elicoidal — APPROVED** [review]
LGTM (but not technical enough to be good judge :wink:)

**Pull request merged**
