### PR TITLE
[BCP][8.0] from 9.0 queue garbage collector methods and cron

### PR DESCRIPTION
**Pull request by thomaspaulb**
Backport of #325

### CODE REVIEW

**Review by guewen — APPROVED** [review]

**Comment by thomaspaulb** [comment]
@guewen Should we just merge this minor fix?

**Review by gurneyalex — APPROVED** [review]

**Comment by a0c** [comment]
What a great day to CLOSE this approved, ready to merge PR... :exploding_head:

**Comment by thomaspaulb** [comment]
@a0c Do you still have an interest in having it merged?

**Pull request closed without merging**
