### PR TITLE
Migrate connector to 12.0

### PR DESCRIPTION
**Pull request by guewen**

### CODE REVIEW

**Review by lmignon — APPROVED** [review]
Thank you @guewen LGTM (Code review only)

**Comment by CGenie** [comment]
Hello,
We're looking forward to v12 of the connector project. Is this pull request complete? I see tests passing :)

**Comment by guewen** [comment]
> We're looking forward to v12 of the connector project. Is this pull request complete? I see tests passing :)

It is supposed to be :)

**Review by simahawk — APPROVED** [review]

**Comment by guewen** [comment]
Merged in https://github.com/OCA/connector/commit/518f86612a9af08bfe4847386bfa01e223a93fcf

**Pull request closed without merging**
