### PR TITLE
[12.0][ADD] connector: new app icon

### PR DESCRIPTION
**Pull request by ruuter**
Since connector adds root menu item, it should have proper icon.
This is most apparent in app drawer provided by web_responsive.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Yes, please!

**Review by guewen — APPROVED** [review]
:green_heart:

**Comment by pedrobaeza** [comment]
Let's go with it for having ASAP:

/ocabot merge minor

**Comment by pedrobaeza** [comment]
Can you please forward-port it to v13?

**Pull request merged**
