### PR TITLE
Dependency repos moved in a subfolder in travis

### PR DESCRIPTION
**Pull request by guewen**
See OCA/maintainer-quality-tools#289

### CODE REVIEW

**Comment by guewen** [comment]
Waiting on OCA/maintainer-quality-tools#289

**Comment by pedrobaeza** [comment]
If you want to try with this branch, change the source of the MQT branch to yours.

**Comment by guewen** [comment]
> If you want to try with this branch, change the source of the MQT branch to yours.

Or just wait :o)

**Comment by pedrobaeza** [comment]
hehe, of course. I restarted Travis to see now that it's merged.

**Comment by guewen** [comment]
umm not working yet, I'll see what happens

**Comment by guewen** [comment]
Oh, it happens that `node_modules` is in the build directory (so inside the repository): `/home/travis/build/OCA/connector` :cry:

**Comment by guewen** [comment]
logs:

```
odoo_root: /home/travis/odoo-8.0

build_path: /home/travis/build/OCA/connector

deps_path: /home/travis/dependencies

deps_repos: []

addons_paths: ['/home/travis/odoo-8.0/openerp/addons', '/home/travis/odoo-8.0/addons', '/home/travis/build/OCA/connector']

addons: ['connector', 'connector_base_product', 'node_modules']
```

**Pull request closed without merging**
