### PR TITLE
Build and push the french documentation

### PR DESCRIPTION
**Pull request by guewen**
Follows #60 and #57.

Once built, it will be available in http://odoo-connector.com/fr and a new menu will allow to select the language.

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:  I suppose that the doc will be available once the PR will be merged.

**Comment by guewen** [comment]
@lmignon yes, the merge will trigger a new build and an update of the docs on odoo-connector.com

**Comment by mdietrichc2c** [comment]
:+1:

**Comment by nbessi** [comment]
:+1:

**Pull request merged**
