### PR TITLE
connector_event: Disable trigger if registry is not ready

### LINKED ISSUE #279: Odoo 11.0 Components Events Installation Problem
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 167, in load_module_graph
    module.with_context(overwrite=overwrite)._update_translations()
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 865, in _update_translations
    self.env['ir.translation'].load_module_terms(mod_names, filter_lang)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_translation.py", line 706, in load_module_terms
    res_lang.load_lang(lang)
  File "/opt/odoo/odoo/odoo/addons/base/res/res_lang.py", line 90, in load_lang
    language.write({'active': True})
  File "/opt/odoo/odoo/odoo/addons/base/res/res_lang.py", line 225, in write
    res = super(Lang, self).write(vals)
  File "/opt/odoo/addons/connector/component_event/models/base.py", line 103, in write
    self._event('on_record_write').notify(record, fields=fields)
  File "/opt/odoo/addons/connector/component_event/models/base.py", line 88, in _event
    collecter = work._component_class_by_name('base.event.collecter')(work)
  File "/opt/odoo/addons/connector/component/core.py", line 290, in _component_class_by_name
    raise NoComponentError("No component with name '%s' found." % name)
odoo.addons.component.exception.NoComponentError: No component with name 'base.event.collecter' found.

I have installed component and also i have installed cache tools 2.0.1 but still I am having this problem. Thank you for your responses

### PR DESCRIPTION
**Pull request by guewen**
During install / upgrade of addons, the odoo registry is recreated and not
flagged as ready. At the end of the odoo registry loading, the registry
of components will be built. If we install component_event from the UI
(not with -i), the component's registry is already flagged as "ready",
but the 'base.event.collecter' component is not yet referenced in it.

Inhibiting the trigger of event when the odoo registry is ready will
prevent this issue. It means that no event will be triggered when the
install or upgrade of addons should trigger them but this was already
the case when using the "-i" install of addons.

Fixes #279

### CODE REVIEW

**Comment by guewen** [comment]
Tests still pass (at least locally), but I didn't tested it for real. It's an attempt to fix #279, so please if you are interested in having this fix, test it thoroughly. (I'm not much concerned by #279 as we never install from the UI)

**Comment by guewen** [comment]
Forgot to mention @berkcirisci @okmuk @lgarcia11 @AttentionalM

**Comment by guewen** [comment]
But well, tests do not pass on Travis, still need a bit of work

**Comment by guewen** [comment]
Updated from the fix in 10.0 #294

**Comment by guewen** [comment]
The one in 10.0 has been merged, can I have some reviews/merge?

**Review by atchuthan — APPROVED** [review]

**Pull request merged**
