### PR TITLE
Migrate component/connector to version 11.0

### PR DESCRIPTION
**Pull request by guewen**

### CODE REVIEW

**Comment by guewen** [comment]
Build is green, unless the generation of the documentation which is still failing with a mysterious "No module named 'odoo'"

**Comment by guewen** [comment]
Travis is green!

**Comment by gurneyalex** [comment]
@guewen maybe you can rebase/squash the fixups ?

**Comment by guewen** [comment]
I squashed the commits

**Comment by lasley** [comment]
https://github.com/guewen/connector/pull/6 for #268

**Comment by lmignon** [comment]
@guewen Take a look at https://github.com/OCA/connector/pull/268/files (https://github.com/OCA/connector/pull/268/files/8a548cad5e00b0f8986cfecd0380076e3007ef5c#r147445091)

**Comment by guewen** [comment]
@lmignon applied the same change

**Comment by lmignon** [comment]
@guewen OK Thank you.

**Review by simahawk — APPROVED** [review]
LGTM

**Comment by simahawk** [comment]
@lmignon @lasley ping :)

**Comment by lasley** [comment]
Hmmm I'm a bit confused here. Is this repo using the old script, where the previous base is kept for the new branch? 

Regardless, I'll upgrade a few connectors in the next few days and give this a functional round. I didn't see anything that stood out in the code on a quick review, but I'll do a more thorough one of those too.

**Comment by guewen** [comment]
> Hmmm I'm a bit confused here. Is this repo using the old script, where the previous base is kept for the new branch?

Yes

**Review by lasley — APPROVED** [review]
Code looks good, thanks @guewen. I have a prelim form of the EasyPost connector working in this on v11, so I'd say functionally 👍  as well

**Comment by lasley** [comment]
@guewen - I notice you've already [performed a squash](https://github.com/OCA/connector/pull/266#issuecomment-334495181), but there's still a lot of commits. Do you want to merge with all of these?

**Review by atchuthan — APPROVED** [review]

**Comment by guewen** [comment]
@lasley made another pass and squashed some additional commits

**Comment by lasley** [comment]
Thanks @guewen! Let there be v11 connector!

**Comment by lukebranch** [comment]
@lasley ,

Apologies in advance for commenting on a PR.

> Code looks good, thanks @guewen. I have a prelim form of the EasyPost connector working in this on v11, so I'd say functionally 👍 as well

Any chance you've got a public repo with this code? I'd be very interested in checking out what you've done regarding 10.0 > 11.0 changes for your connector.

**Pull request merged**
