### PR TITLE
[17.0][MIG] test_connector: Migration to 17.0

### PR DESCRIPTION
**Pull request by nguyenminhchien**
Depends on:
* https://github.com/OCA/connector/pull/476

### CODE REVIEW

**Comment by simahawk** [comment]
@nguyenminhchien the migration of test* modules make little sense out of the PR where you migrate the module. There's no way to understand if the module being migrated is failing or not until you look at all the others PRs and re-trigger their jobs.

**Comment by nguyenminhchien** [comment]
> @nguyenminhchien the migration of test* modules make little sense out of the PR where you migrate the module. There's no way to understand if the module being migrated is failing or not until you look at all the others PRs and re-trigger their jobs.

ok, i will merge this one with https://github.com/OCA/connector/pull/476

**Comment by nguyenminhchien** [comment]
Merged the migration of `test_connector` into https://github.com/OCA/connector/pull/476

**Pull request closed without merging**
