### PR TITLE
[17.0][MIG] connector + test_connector: Migration to 17.0

### PR DESCRIPTION
**Pull request by nguyenminhchien**
Ref: BSRD-701
Depends on:
* https://github.com/OCA/connector/pull/475
* https://github.com/OCA/queue/pull/593

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Comment by gurneyalex** [comment]
@nguyenminhchien all the unreleased dependencies have been merged, can you update the PR?

**Comment by nguyenminhchien** [comment]
> @nguyenminhchien all the unreleased dependencies have been merged, can you update the PR?

@gurneyalex updated.

**Pull request merged**
