### PR TITLE
ADD icon

### PR DESCRIPTION
**Pull request by ljimenezsidoo**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you provide the corresponding SVG file?

**Comment by ljimenezsidoo** [comment]
@pedrobaeza Sorry I don't have the svg file because the web where I did not give me the svg file

**Comment by pedrobaeza** [comment]
@acm1pt-colorado I have created another icon with the SVG source.

@sergio-teruel @simahawk @guewen

**Review by lasley — APPROVED** [review]
❤️  it

**Review by simahawk — APPROVED** [review]
:sunglasses:

**Review by lmignon — APPROVED** [review]

**Review by atchuthan — APPROVED** [review]

**Comment by guewen** [comment]
Excellent, I like it a lot!

Thanks

**Review by guewen — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please cherry-pick the commit on the 10.0 migration in OCA/queue

**Comment by pedrobaeza** [comment]
Or do you think we need another icon for representing the queue? This one is more oriented to the word "connector". If you like another one, just pick one FontAwesome icon and I'll prepare it.

**Comment by guewen** [comment]
> Or do you think we need another icon for representing the queue? This one is more oriented to the word "connector". If you like another one, just pick one FontAwesome icon and I'll prepare it.

What about http://fontawesome.io/icon/tasks/ ?
Or http://fontawesome.io/icon/angle-double-right/ ?

**Comment by lasley** [comment]
👍  on `fa-tasks`

**Comment by pedrobaeza** [comment]
Unfortunately that icon is over-used and I don't think we should use it here also: https://github.com/odoo/odoo/search?utf8=%E2%9C%93&q=fa-tasks&type=

**Comment by pedrobaeza** [comment]
This can be an alternative: http://fontawesome.io/icon/list/

**Comment by lasley** [comment]
😆  I guess a lot of other people gave a lot of 👍  on `fa-tasks`! It's a good icon 🚀 

I tend to think of a queue as something stacked, like a deck of cards to be drawn in order. In this light, I think `fa-list` looks good too

**Comment by guewen** [comment]
Ok then `fa-list` is a good alternative

> I tend to think of a queue as something stacked, like a deck of cards to be drawn in order. In this light, I think fa-list looks good too

Exactly :)

**Comment by lmignon** [comment]
:+1: for 'fa-list'

**Comment by simahawk** [comment]
:+1: `fa-list`

**Comment by pedrobaeza** [comment]
Icon for 10.0 queue module added here: https://github.com/OCA/queue/pull/15

**Pull request merged**
