### PR TITLE
[12.0][Connector] Make connector checkpoint compatible in multi company environment

### PR DESCRIPTION
**Pull request by florian-dacosta**
I have some right access errors on multi company environment. As there is no company_id on `connector_checkpoint`, when company A sees checkpoint that should belong to company B, I have some access error on linked records (from field `backend_id` field for instance).

I had to do a migration script because when updating the module and creating the new computed company_id field, the backends models are not loaded yet and Odoo can't find it in registry.

@guewen

### CODE REVIEW

**Review by guewen — APPROVED** [review]
Looks good, but you have to fix the lint:

connector/migrations/12.0.1.1.0/pre-migration.py:3:1: E302 expected 2 blank lines, found 1

**Review by lmignon — APPROVED** [review]
LGTM

**Review by bealdav — APPROVED** [review]
code review

**Comment by florian-dacosta** [comment]
Sorry for the delay, I had not seen the answers!
I have fixed the lint error, it is all green!

**Pull request merged**
