### PR TITLE
[IMP] connector-runner: graceful stop mechanism

### PR DESCRIPTION
**Pull request by sbidoul**
The previous version was relying a daemon thread, which was ok, except it would continue to enqueue jobs while the server was stopping, and such jobs would never start.

This in combination with https://github.com/odoo/odoo/pull/6738 should ensure jobs are left in a consistent state upon normal shutdown. Only a hard crash would leave jobs in a started state in which case those must be requeued manually.

### CODE REVIEW

**Comment by guewen** [comment]
Very well observed! I confirm that `started` jobs are no longer interrupted with this patch and odoo/odoo#6738. 

```
2015-05-20 11:44:16,198 14980 DEBUG openerp_dev openerp.addons.connector.controllers.main: <Job 341d9f10-09b4-40c7-9565-c17a09a8d1c0, priority:10> done
2015-05-20 11:44:16,202 14980 INFO openerp_dev openerp.service.server: Worker (14980) exiting. request_count: 8, registry count: 1.
```

Great! Just waiting on an answer on odoo/odoo#6738 now...

**Comment by lmignon** [comment]
:+1:

**Comment by guewen** [comment]
@lmignon did you backported  this PR in v7 too?

**Comment by lmignon** [comment]
@guewen not yet. it will be done tomorrow as I need it

**Comment by sbidoul** [comment]
In v7 the runner is a separate process? In which case it should not be necessary to backport this: killing the runner before OpenERP should be sufficient.

**Comment by guewen** [comment]
> In v7 the runner is a separate process? In which case it should not be necessary to backport this: killing the runner before OpenERP should be sufficient.

It makes sense.

@sbidoul If I understand correctly, we can already merge this one even if odoo/odoo#6738 is not merged yet. It won't prevent jobs to be interrupted, but it will prevent to push new jobs when exiting, is it correct?

**Comment by lmignon** [comment]
@sbidoul you're right. The one I need to back port is https://github.com/odoo/odoo/pull/6738

**Comment by sbidoul** [comment]
> @sbidoul https://github.com/sbidoul If I understand correctly, we can
> already merge this one even if odoo/odoo#6738
> https://github.com/odoo/odoo/pull/6738 is not merged yet. It won't
> prevent jobs to be interrupted, but it will prevent to push new jobs when
> exiting, is it correct?
> 
> Correct.

**Comment by guewen** [comment]
:+1: 
Thanks!

**Pull request merged**
