### PR TITLE
[IMP] job view

### PR DESCRIPTION
**Pull request by bealdav**
gain space to see task and except info

job

@guewen Are you ok for that

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by chafique-delli** [comment]
:+1:

**Comment by Viggor** [comment]
:+1:

**Comment by guewen** [comment]
> @guewen Are you ok for that

I am. Anyway it has  been merged. ;-)
Thanks @bealdav

**Pull request merged**
