### PR TITLE
Porting job_uuid in context to V9

### PR DESCRIPTION
**Pull request by nicolas-petit**
See the following pull request for V8 version:
https://github.com/OCA/connector/pull/172/files

### CODE REVIEW

**Comment by lasley** [comment]
Hi @nicolas-petit - thanks for the submission. Would it be possible to instead cherry pick the relevant commits from the 8.0 branch? While I admittedly prefer the one commit that we have here vs the multiple there, using the cherry-picks makes it easier to identify the change sets are actually the same from a high level.

**Comment by nicolas-petit** [comment]
Thank your for your feedback @lasley 
I revised this pull request using cherry-picking.

**Comment by lmignon** [comment]
:+1: (Code review)

**Comment by sebalix** [comment]
:+1:

**Comment by lasley** [comment]
Thanks for the update @nicolas-petit 👍

**Pull request merged**
