### PR TITLE
Correct PR #81

### PR DESCRIPTION
**Pull request by guewen**
DOCS is set to 0 or 1 so check that and not if DOCS is set/unset

### CODE REVIEW

**Comment by pedrobaeza** [comment]
These strange shell commands... :+1:

**Comment by guewen** [comment]
Transifex says 
> WARNING! Transifex password not recognized- exiting early.

**Comment by yvaucher** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by guewen** [comment]
This time it is green

**Pull request merged**
