### PR TITLE
[IMP] add the posibility to merge the job. This is very usefull for the ...

### PR DESCRIPTION
**Pull request by sebastienbeau**
...Magento case, indeed the api is very slow and we have to avoid the useless call to Magento, if we modify a binding and a product only one job should be created in order to avoid 2 call to Magento instead of one

You can take a look to this exemple : https://github.com/OCA/connector-magento/pull/23

### CODE REVIEW

**Comment by guewen** [comment]
Discussed off-topic, needs to be done in another manner, with a `mergeable` declaration on the jobs using a decorator. Optionally, a function may be given that explicit how the kwargs are merged.

**Comment by nbessi** [comment]
May we close this PR and make a new one when ready?

**Comment by rvalyi** [comment]
great, I want it too.

**Comment by lmignon** [comment]
Can we close this PR? It seems to be obsolete and there is no more activity?

**Comment by hbrunn** [comment]
@lmignon after three months, I'd simply do so if I were you. Or don't you have permissions?

**Comment by lmignon** [comment]
@hbrunn I've the permission but I prefer to ask by courtesy to the author ho has invested to enhance the connector :smirk:

**Comment by hbrunn** [comment]
@lmignon being a python programmer, I think it's easier to ask for forgiveness than permission ;-)

**Comment by sebastienbeau** [comment]
For sure you can close it. As I am not available to work on it for now

**Pull request closed without merging**
