### PR TITLE
[16.0][MIG] component + test_component: Migration to 16.0

### PR DESCRIPTION
**Pull request by asierneiradev**
#440 : component + test_component

### CODE REVIEW

**Comment by asierneiradev** [comment]
Hi @flachica  ! 
can you help me to push this migration?
How do you see the PR?
Best regards

**Review by simahawk — APPROVED** [review]
LG

**Comment by simahawk** [comment]
Can you rebase pls? I'd like to see runboat build running and likely we'll have a problem w/ pre-commit as we have to sync from the template.

**Comment by asierneiradev** [comment]
Hi @simahawk !
Performed the rebase and it looks like all the checks have been executed.
Do you need any more adjustments to be made?
Best regards and thanks for the follow up

**Comment by StefanRijnhart** [comment]
Please include https://github.com/OCA/connector/pull/448, which was merged in the 15.0 branch recently.

**Comment by asierneiradev** [comment]
Hi @StefanRijnhart

Is already included. Best regards !

> Please include #448, which was merged in the 15.0 branch recently.


Selección_027

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Pull request merged**
