### PR TITLE
[13.0][MIG] component, component_event, test_component: Migration to 13.0

### PR DESCRIPTION
**Pull request by sebalix**
Supersedes #355 (I didn't get right access on @damdam-s branch sadly)

Commits rebased and squashed (merge commits have also been removed).

The following section of `.travis.yml` has been removed:
```yml
services:
  - postgresql
```

ping @simahawk @lmignon @guewen

### CODE REVIEW

**Review by simahawk — APPROVED** [review]

**Review by lmignon — APPROVED** [review]

**Comment by lmignon** [comment]
This one has been successfully tested with OCA/rest-framework/pull/53. (Functional Tests) IMO ready to merge
@guewen

**Comment by simahawk** [comment]
I restarted runbot build as it was stalled

**Comment by sebalix** [comment]
@simahawk runbot is still stalled. Don't know what happens...

**Comment by simahawk** [comment]
@gurneyalex can you check what's wrong on runbot? If you go to logs you get 404 :man_shrugging:

**Review by guewen — APPROVED** [review]
:tada:

**Comment by guewen** [comment]
We can resolve the runbot issue later :)

**Pull request merged**
