### PR TITLE
[ADD] [WIP] Migration script for connector module

### PR DESCRIPTION
**Pull request by cubells**
cc @Tecnativa

### CODE REVIEW

**Comment by guewen** [comment]
Could you explain what queue_job_comp_rule is?

**Comment by cubells** [comment]
this:

https://github.com/OCA/connector/blob/9.0/connector/security/connector_security.xml#L20

**Comment by cubells** [comment]
Maybe it's not needed because now is here:

https://github.com/OCA/queue/blob/10.0/queue_job/security/security.xml#L20

What do you think?

**Comment by guewen** [comment]
could you filter on the module as well? `module = 'connector'`

**Comment by guewen** [comment]
Is it gonna work for migration between 9.0 and 10.0?

**Comment by cubells** [comment]
Yes, it's for migration between 9.0 and 10.0.

**Comment by guewen** [comment]
The group should be removed as well, as you say, it has been moved in queue

**Comment by pedrobaeza** [comment]
@cubells you haven't got the full picture of a migration of this module from v9 to v10. Let me explain: in v10, the module has been unfolded in 2: `queue_job` in OCA/queue, and `connector` here, which depends on the first.

As there's no way to know which features do you need for your migrated v9 DB, the strategy should be:

* Rename on OpenUpgrade `connector` to `queue_job` in apriori.py.
* Include a migration script on v10 `queue_job` that looks for module `connector` and change its state to `to upgrade` (this is the real value to put).
* You have to analyze changes from v9 to v10, including noupdate deleted records and so on, and put it on the proper module (queue_job or connector), but in this case I see that you are looking in v10 queue_job module, which I don't see correct.

**Comment by cubells** [comment]
ok. I redo this pr after analyze all.

**Comment by cubells** [comment]
Related: https://github.com/OCA/OpenUpgrade/pull/1038

**Comment by cubells** [comment]
Related: https://github.com/OCA/queue/pull/20

**Comment by cubells** [comment]
@guewen 
this pr is not necessary because all noupdate xml-ids are moved to module connector or queue_job in v. 10.0

With these prs
https://github.com/OCA/OpenUpgrade/pull/1038
https://github.com/OCA/queue/pull/20
all is done.

I close this pr.

**Pull request closed without merging**
