### PR TITLE
Default binder

### PR DESCRIPTION
**Pull request by guewen**
Follows #76.

### CODE REVIEW

**Comment by guewen** [comment]
This is the change I want to promote: https://github.com/OCA/connector/commit/1525a4ad06c0d02f78dbdc1568a7ab4274a03e32

As a call to `browse()` does not hit the database until we first access one of the fields (other than `id`), I think it is better to always returns a recordset. The API will be easier to use and it reduces the chances of developer errors, we have only one possible type in the return and one knows that she has always to call `.id` on the result of `to_openerp()` when she wants the `id` of a binding. It is also inline with the new API which returns recordsets instead of ids in `search()`.

**Comment by lmignon** [comment]
:+1: (code review)

**Comment by guewen** [comment]
Rebased. I would :heart:  to get this PR merged.

**Comment by sebastienbeau** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: 
Yeeesssss, I totaly approve this PR

**Comment by bguillot** [comment]
of course :+1: !
I missed this one I approved the previous one ...

**Pull request merged**
