### PR TITLE
[FIX][connector] confusion between self.env from test of connector and s...

### PR DESCRIPTION
**Pull request by JonathanNEMRY**
...elf.env recently added into tearDown of common.py

see https://github.com/odoo/odoo/commit/908252ec88cd4516ee84fdf93c07d09f51a45413

### CODE REVIEW

**Comment by guewen** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by adrienpeiffer** [comment]
:+1:

**Comment by guewen** [comment]
Just waiting after travis...

**Comment by JonathanNEMRY** [comment]
Seems that `test_pylint` failed but I don't think this is related to my changes

**Comment by guewen** [comment]
That's right, I will work on the pylint warnings soon.

**Pull request merged**
