### PR TITLE
[17.0][MIG] component_event: Migration to 17.0

### PR DESCRIPTION
**Pull request by nguyenminhchien**
Ref: BSRD-701
Depend on:
* https://github.com/OCA/connector/pull/474

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Review by simahawk — COMMENTED** [review]
LG

**Comment by gurneyalex** [comment]
@nguyenminhchien I'm merging https://github.com/OCA/connector/pull/474 -> you should be able to rebase and remove the unreleased dependency, and then I'll merge this one.

**Comment by nguyenminhchien** [comment]
> @nguyenminhchien I'm merging #474 -> you should be able to rebase and remove the unreleased dependency, and then I'll merge this one.

@gurneyalex i have rebase, thanks.

**Pull request merged**
