### PR TITLE
[16.0][MIG] component_event: Migration to 16.0

### PR DESCRIPTION
**Pull request by asierneiradev**
#440 

Dependency : 

- [x] [component](https://github.com/OCA/connector/tree/16.0/component)

### CODE REVIEW

**Comment by flotho** [comment]
Hi,
Thanks for the job done.
Any chance to rebase because `component` module is available in main 16.0

**Comment by asierneiradev** [comment]
Hi @flotho !

Rebase done on the 16.0 branch.

Regards, and thank you very much

**Comment by flotho** [comment]
with pleasure, I'm actually testing your 2 PR for a reboot of https://github.com/OCA/infrastructure/pull/18

**Comment by asierneiradev** [comment]
Good afternoon @flotho ,
what is the condition of this PR?
thank you very much

**Comment by asierneiradev** [comment]
Hi @sbidoul  @simahawk ,

Do you think it would be ready to merge?
Thank you very much

**Review by lmignon — APPROVED** [review]
Thank you @asierneiradev LGTM (Code review)

**Review by simahawk — APPROVED** [review]
LG

**Pull request merged**
