### PR TITLE
[REF]8.0 product template view

### PR DESCRIPTION
**Pull request by flotho**
Add oca icons
readd page in notebook in product template

### CODE REVIEW

**Comment by guewen** [comment]
Thanks!
Could you remove the commits 58834c6 and 1524691 with `git rebase -i d8e4878^`?

**Comment by flotho** [comment]
@guewen done!

**Comment by gurneyalex** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by damdam-s** [comment]
:+1:

**Pull request merged**
