### PR TITLE
Make the workers process work in a rolling order

### PR DESCRIPTION
**Pull request by guewen**
Assign an index to each worker, then at each turn, add a delay relative to
their index modulo the population.

This way, each worker has an equal opportunity to take jobs.

Example with 4 workers
- loop 1
  - worker 1: sleep 15 + 1
  - worker 2: sleep 15 + 2
  - worker 3: sleep 15 + 3
  - worker 4: sleep 15 + 0
- loop 2
  - worker 1: sleep 15 + 2
  - worker 2: sleep 15 + 3
  - worker 3: sleep 15 + 0
  - worker 4: sleep 15 + 1
- loop 3
  - worker 1: sleep 15 + 3
  - worker 2: sleep 15 + 0
  - worker 3: sleep 15 + 1
  - worker 4: sleep 15 + 2
- loop 4
  - worker 1: sleep 15 + 0
  - worker 2: sleep 15 + 1
  - worker 3: sleep 15 + 2
  - worker 4: sleep 15 + 3

### CODE REVIEW

**Comment by guewen** [comment]
@lmignon looking forward to have your opinion and tests if possible

**Comment by lmignon** [comment]
@guewen  thank you for the proposal.  I'll make a try on monday and keep you informed.

**Comment by yvaucher** [comment]
@lmignon any comment some mondays later ? :wink: 

:+1: (code review)

**Comment by lmignon** [comment]
@guewen @yvaucher Sorry, this PR is fallen in the limbo of nowhere... IMO with the new runner, the change is no more required

**Comment by guewen** [comment]
It would only improve the old poor workers and not the new shiny runner, but maybe we can give some cuddle to the old workers before the day we'll savagely kill them.

Nah, seriously if people suffer from the problem this PR aims to reduce, they just have to use the new runner.

**Pull request closed without merging**
