### PR TITLE
Improved Submapping documentation

### PR DESCRIPTION
**Pull request by andreinl**
Added example from https://github.com/OCA/connector/issues/336#issuecomment-538964301 thread to official documentation

### CODE REVIEW

**Review by guewen — APPROVED** [review]
Thanks for the update!

**Comment by pedrobaeza** [comment]
@guewen ocabot stuck. Please relaunch

**Comment by guewen** [comment]
It seems runbot is stuck on all the builds of connector, may be better now, retrying.

/ocabot merge nobump

**Comment by guewen** [comment]
Stuck again

**Comment by pedrobaeza** [comment]
Not sure what's happening... @sbidoul can it be that if Travis lasts a lot, does it got stuck?

**Comment by sbidoul** [comment]
@pedrobaeza @guewen I suspect its due to github-pages reporting a failed status. I'll add more logging to the bot and investigate.

**Comment by pedrobaeza** [comment]
Thanks for checking

**Comment by guewen** [comment]
Thanks @sbidoul :green_heart:

**Pull request merged**
