### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### OCA/connector now has a Chat Room on Gitter

@guewen has just created a chat room. You can visit it here: [https://gitter.im/OCA/connector](https://gitter.im/OCA/connector?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/OCA/connector?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

Maybe it's better to put it with the rest of badges.

**Comment by guewen** [comment]
@pedrobaeza I just saw the PR, I wasn't aware that Gitter creates the PR for the badges without asking.

Is it something we want on the OCA projects? It could be useful, but yet another channel to observe after GitHub itself, the mailing lists, the irc channels.

**Comment by guewen** [comment]
Anyway I close this PR and I can still propose another one with the badge in the correct place if we want it.

**Comment by pedrobaeza** [comment]
Well, it's another option very accesible. More than the IRC channel, but maybe we should talk about this on the community list.

**Pull request closed without merging**
