### PR TITLE
Wrong arguments position in a log message

### PR DESCRIPTION
**Pull request by guewen**

### CODE REVIEW

**Comment by sbidoul** [comment]
:+1: 

So you managed to trigger that warning?

**Comment by guewen** [comment]
> So you managed to trigger that warning?

Yes! :-)
I was investigating #68 and called the controller directly on a job such as `/connector/runjob?job_uuid=e3ecfa2e-e425-481c-bc0d-3d1cc64f2c02`

**Comment by guewen** [comment]
BTW would it be "dangerous" if we allowed to call the controller directly on `pending` jobs?

**Comment by sbidoul** [comment]
> BTW would it be "dangerous" if we allowed to call the controller directly
> on pending jobs?
> 
> Someone knowing uuids could then start any job. An external attacker would have to guess uuids to do any harm so maybe it's not dangerous indeed. In that case the worst he could do is a DoS by launching many jobs at once.

Are uuids guessable? If not we could maybe skip the enqueued state.

-sbi

**Comment by guewen** [comment]
I would say very difficult to predict, if possible, but they are not designed _in the aim_ to be unpredictable. Anyway, I was thinking about that when I was debugging, just to check if jobs were runnable, but I see no real application otherwise. So maybe we can discuss about that again if we have a concrete use case for that.

**Comment by lmignon** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
