### PR TITLE
Allow to build a ConnectorSession directly from an Odoo Environment

### PR DESCRIPTION
**Pull request by guewen**
Replace the verbose: ConnectorSession(self.env.cr, self.env.uid, context=self.env.context)
By: ConnectorSession.from_env(self.env)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by sbidoul** [comment]
:+1: (code review only)

**Comment by guewen** [comment]
Wow, that was fast!

**Pull request merged**
