### PR TITLE
[16.0][MIG] connector_base_product: Migration to 16.0

### PR DESCRIPTION
**Pull request by asierneiradev**
#440 

Dependency : 

- [x] https://github.com/OCA/connector/pull/442

### CODE REVIEW

**Comment by asierneiradev** [comment]
Wouldn't it be necessary to first have merge `connector` in order to remove the dependency in `test-requirements.txt`?

**Comment by asierneiradev** [comment]
Hi @simahawk @sbidoul  !
Branch rebased and test-requirements.txt dependency removed.
Could it be merged ?
Thank you very much

**Comment by asierneiradev** [comment]
Hi @simahawk ,

would it be possible to launch again the command to merge?

By removing the associated dependency, the entire repository would be migrated.

Thank you very much for your time, if I can help you in any way I will be glad to do it.

Regards

**Comment by simahawk** [comment]
@asierneiradev you shouldn't touch .copier-answers manually. Please trash the last commit and rebase on 16.0

**Review by simahawk — COMMENTED** [review]
LG otherwise

**Comment by asierneiradev** [comment]
> @asierneiradev you shouldn't touch .copier-answers manually. Please trash the last commit and rebase on 16.0

Done! 
But now the tests are failing, and I can't understand why. 
Could you help me?

**Comment by simahawk** [comment]
I think there's a problem w/ a test in test_component. The class `TestEventWorkContext` does not inherit from Odoo base case - because there's actually NO need for it - but the odoo test suite runner expects all test class to have the meta class MetaCase which sets the `test_module` attribute.
I'm re-running a build on 16.0 to verify it.

**Comment by simahawk** [comment]
Reproduced on 16.0 https://github.com/OCA/connector/actions/runs/4250721530/jobs/7501676448#step:8:103
I'll provide a fix.

**Comment by simahawk** [comment]
FYI I'm stuck here https://github.com/OCA/connector/pull/461

**Comment by simahawk** [comment]
Fix here https://github.com/odoo/odoo/pull/114007

**Comment by asierneiradev** [comment]
> Fix here [odoo/odoo#114007](https://github.com/odoo/odoo/pull/114007)

Great job @simahawk !
Thank you very much for the help and your time.
I will keep an eye on the evolution of the [FIX](https://github.com/odoo/odoo/pull/114007). 
Once it is merged, I will include it by rebasing on 16.0.

Thanks for everything, best regards!

**Comment by asierneiradev** [comment]
Hi @simahawk !

Thanks to your [FIX](https://github.com/OCA/connector/pull/462), I have relaunched the tests and it seems ready to be merged and ultimately leave the [connector](https://github.com/OCA/connector) module completely migrated.

Thank you very much for your help

**Review by simahawk — APPROVED** [review]

**Pull request merged**
