### PR TITLE
11.0 backport pull 387

### PR DESCRIPTION
**Pull request by agent-z28**

### CODE REVIEW

**Comment by agent-z28** [comment]
@guewen 
There's only the linter failing with code i didn't modify.
All other seems to be propper. Please check if this MR is good!
I need it to backport the edi_oca to v11

connector/components/synchronizer.py:164: [E8102(invalid-commit), GenericExporter.run] Use of cr.commit() directly - More info https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#never-commit-the-transaction

connector/components/synchronizer.py:352: [E8102(invalid-commit), GenericExporter._export_dependency] Use of cr.commit() directly - More info https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#never-commit-the-transaction

**Comment by guewen** [comment]
The linter may be a new check for 11.0, could you add `  # pylint: disable=E8102` on the `cr.commit()` lines as it was done in more recent versions, so the build is green? https://github.com/OCA/connector/blob/9f04ca1897991ef639d0be6f8f48cea805314871/connector/components/synchronizer.py#L165

**Comment by agent-z28** [comment]
@guewen i changed the lines. The linter still counts 2 errors. can you tell me where they come from?
I don't see anything

**Comment by guewen** [comment]
flake8 fails because of

```
connector/components/synchronizer.py:164:58: W291 trailing whitespace
connector/components/synchronizer.py:352:70: W291 trailing whitespace
```

I can't see why pylint fails, but maybe the failure is actually only because of flake8?

**Comment by agent-z28** [comment]
@guewen now check again :)

**Review by guewen — APPROVED** [review]
Thanks!

**Comment by agent-z28** [comment]
@guewen who can give the missing approval ? i have a related MR in the EDI  repos which depends on this one

**Review by bizzappdev — APPROVED** [review]

**Comment by agent-z28** [comment]
@guewen let's merge ?

**Comment by guewen** [comment]
/ocabot merge minor

Yep 👍

**Pull request merged**
