### PR TITLE
[FIX] str to ustr

### PR DESCRIPTION
**Pull request by leemannd**
Fix error if we have a unicode

### CODE REVIEW

**Comment by elicoidal** [comment]
runbot is angry...

**Review by elicoidal — APPROVED** [review]

**Comment by leemannd** [comment]
@elicoidal Don't know why.

**Comment by elicoidal** [comment]
I just forced a rebuild. Let's wait

**Comment by elicoidal** [comment]
@gurneyalex No way to rebuild the runbot: any advice?

**Comment by gurneyalex** [comment]
@elicoidal I just forced a rebuild.

**Comment by elicoidal** [comment]
@gurneyalex Still not possible to use it.

**Comment by lasley** [comment]
The same issue is on Travis, it looks like there is nothing to test - https://travis-ci.org/OCA/connector/jobs/202678951#L316

Current build looks fine. Maybe try rebasing onto 9.0?

**Comment by lasley** [comment]
Oh well this is because the PR is targeting 10.0, which isn't released and is not installable.

**Comment by simahawk** [comment]
@leemannd can you fix PR's target? :)

**Comment by lasley** [comment]
Just changing the target will add a bunch of commits to the PR because it is based on 10. Will also need to reset the branch to 9.0, then cherry-pick the 6cd50e218c63c351f17141fe7f4c815147a55c2b

**Comment by leemannd** [comment]
@lasley Was testing the V10.0 Doing this week a patch for the 9.0

**Comment by guewen** [comment]
I included this commit in #211

**Comment by leemannd** [comment]
as it is on @guewen PR, closing it and doing a new one for V9

**Pull request closed without merging**
