### PR TITLE
[FIX] seconds defaults to RETRY_INTERVAL when no retry_pattern

### PR DESCRIPTION
**Pull request by lefeverd**
Merge Proposal fixing issue #102

### CODE REVIEW

**Comment by guewen** [comment]
Perfect! Thanks :+1:

**Comment by lmignon** [comment]
:+1:  seems this error only occurs with the old worker.

**Comment by lefeverd** [comment]
@oca-clabot CLA is on its way.
@lmignon I had the error also with the jobrunner (if that's what you meant).
@guewen Thanks to you!
On an unrelated subject I had an issue when trying to set a retry_pattern in the decorator of a job like:
job(retry_pattern={0: 20})
It is not taken into account, and even when I break in the job decorator, the parameter is None... Maybe I missed something? Should I open an issue?

**Comment by guewen** [comment]
@lefeverd ouch you are right

Here: https://github.com/OCA/connector/blob/8.0/connector/queue/job.py#L702
The argument should be passed along...

Would be marvellous if a few tests for that could be added :relaxed:

**Comment by sbidoul** [comment]
ICLA ok

**Comment by lefeverd** [comment]
@guewen Indeed, I missed it, thanks.
Do you already plan to fix it? If not I can propose a PR (and maybe include some tests).
@sbidoul Thank you!

**Comment by guewen** [comment]
@lefeverd I'm leaving this evening for 2 weeks with no or nearly no internet access so I would be glad if you could propose a PR

**Pull request merged**
