### PR TITLE
[REF] write function - more modularity

### PR DESCRIPTION
**Pull request by gfcapalbo**
Small refactoring of the write method in queue/model.py

I found my self in the necessity to write a module that silenced some error notifications that were bothering the client. I could not do a clean inheritance the way write() is structured now. I am proposing a refactoring to allow the write function to accept more future modularity.

Ideally to avoid the situation I found myself in we should have:

``` python
def write(self):
    self.pre_write()
    res=SUPER
    self.post_write()
    return res   



```

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash to one commit. Why not including finally the pre_write?

**Comment by gfcapalbo** [comment]
Commits squashed.

**Comment by guewen** [comment]
Could you show an example of what it allows to do that you couldn't do before?

**Comment by lasley** [comment]
Thanks for the submission @gfcapalbo - I agree that a note on what this allows before/after would be excellent.

**Comment by guewen** [comment]
Please re-open in case you still need it and have more details on the intent.

**Pull request closed without merging**
