### PR TITLE
Add travis and meta project files

### PR DESCRIPTION
**Pull request by bwrsandman**
Travis, coverage, License at Readme
### Note:

The travis tests will not pass with master since:
1. code is not PEP8
2. Modules fail to install with 8.0:
   
   ``` python
   ImportError: cannot import name PG_CONCURRENCY_ERRORS_TO_RETRY
   ```

### CODE REVIEW

**Comment by guewen** [comment]
Thanks! I won't merge before we totally switch to GitHub otherwise the mirroring from Launchpad will fail.
But I'm looking forward to merge it and my first PR will be to fix the PEP8, then compatibility with odoo 8.0.

**Comment by bwrsandman** [comment]
Sounds good!

**Comment by guewen** [comment]
I will consider this project as a pilot for the migration, so I will be able to merge this PR :heart_eyes:

**Comment by bwrsandman** [comment]
FYI: the following error can be ignored, it won't cause travis to fail.

```
2014-06-26 14:26:10,308 19274 ERROR test openerp.addons.base.ir.ir_mail_server: Mail delivery failed via SMTP server 'localhost'.
```

**Pull request merged**
