### PR TITLE
Release 3.2.0

### PR DESCRIPTION
**Pull request by guewen**
Updated the changelog and the authors list from the git logs.

### CODE REVIEW

**Comment by guewen** [comment]
I propose to remove the qualifiers on the authors list such as `(tiny change)` because it may seem arbitrary whether a change is a small change or not and finally we (I) don't care, they are contributors, period.

**Comment by gurneyalex** [comment]
:+1:

**Comment by damdam-s** [comment]
:+1:

**Comment by sbidoul** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
