### PR TITLE
[15.0][MIG] connector_base_product: Migration to 15.0

### PR DESCRIPTION
**Pull request by flachica**
Related PRs on the same subject

https://github.com/OCA/sale-workflow/pull/2005
https://github.com/OCA/connector-prestashop/pull/151
https://github.com/OCA/connector-ecommerce/pull/70
https://github.com/OCA/server-tools/pull/2334
https://github.com/OCA/product-attribute/pull/1070
https://github.com/OCA/product-attribute/pull/1069

### CODE REVIEW

**Comment by flachica** [comment]
I can't solve the [runboat error](https://runboat.odoo-community.org/api/v1/builds/b1eb8af2c-5b5d-4a1b-83de-6670007c408b/init-log). Can someone give me a clue /cc @guewen

**Comment by flachica** [comment]
> I can't solve the [runboat error](https://runboat.odoo-community.org/api/v1/builds/b1eb8af2c-5b5d-4a1b-83de-6670007c408b/init-log). Can someone give me a clue /cc @guewen

Finally, after accepting other dependent PRs, they have passed the tests

**Comment by john-herholz-dt** [comment]
What is missing here?

**Comment by flachica** [comment]
> What is missing here?

Is needed two reviewers and one PSC can accept the PR

**Comment by rvalyi** [comment]
Hello @flachica I have no problem with your change and I believe it is correct. However, the checks won't pass because the CI metafiles are not up to date in this v15 connector repo. The runbot is decommissioned and replaced by runboat. Somebody should remove the .travis.yml and add a github action folder like [.github/workflows](https://github.com/OCA/account-invoicing/tree/15.0/.github/workflows)
all metafiles can be seen in https://github.com/OCA/maintainer-quality-tools

Once a PR is made to fix these metafiles, I would say you could rebase your PR and if checks pass it will have more chances to be merged (I would approve it at least).

**Comment by flachica** [comment]
> Hello @flachica I have no problem with your change and I believe it is correct. However, the checks won't pass because the CI metafiles are not up to date in this v15 connector repo. The runbot is decommissioned and replaced by runboat. Somebody should remove the .travis.yml and add a github action folder like [.github/workflows](https://github.com/OCA/account-invoicing/tree/15.0/.github/workflows) all metafiles can be seen in https://github.com/OCA/maintainer-quality-tools
> 
> Once a PR is made to fix these metafiles, I would say you could rebase your PR and if checks pass it will have more chances to be merged (I would approve it at least).

All done! Thanks for your review @rvalyi

**Comment by flachica** [comment]
Any problem with this PR?

**Comment by simahawk** [comment]
commits are messed up, please rebase and keep the mig changes in the last one, thanks!

**Comment by flachica** [comment]
> commits are messed up, please rebase and keep the mig changes in the last one, thanks!

Rebase done, thanks!

**Comment by simahawk** [comment]
the 1st commit is still wrong. Contains migration changes https://github.com/OCA/connector/pull/428/commits/1e5d87fc5dba1d293ffb4b638bb095c44d8a1cc2 
I'd rollback the 2 commits and stage only what's needed manually.

**Comment by flachica** [comment]
I migrated the module step by step. Forced push the changes. Can review, please @simahawk

**Comment by simahawk** [comment]
@flachica better now. Can you rewrite the commit msg to `connector_base_product: Migration to 15.0`? Thanks!

**Comment by flachica** [comment]
> @flachica better now. Can you rewrite the commit msg to `connector_base_product: Migration to 15.0`? Thanks!

Done

**Comment by simahawk** [comment]
"[Migration to 15.0](https://github.com/OCA/connector/pull/428/commits/f4e2764ba629c8b5f89fe2fb12c8a86675ec788b)" of what? As per guidelines and per my msg above, pls include the module name :pray:

**Comment by flachica** [comment]
> "[Migration to 15.0](https://github.com/OCA/connector/pull/428/commits/f4e2764ba629c8b5f89fe2fb12c8a86675ec788b)" of what? As per guidelines and per my msg above, pls include the module name pray

Re done

**Comment by flachica** [comment]
@simahawk One question, what guidelines are you referring to?

**Comment by simahawk** [comment]
Search for "OCA migration guidelines" and you should land on these pages

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0
https://github.com/OCA/maintainer-tools/wiki#migration
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst

**Comment by flachica** [comment]
Fixed message

**Review by xAdrianC-Kernet — APPROVED** [review]

**Comment by flachica** [comment]
In order to finish migrating the Prestashop connector I need this PR to be merged. It has one approval. Any PSC check it out? /cc @simahawk @gurneyalex

**Comment by asierneiradev** [comment]
Good job @flachica !
Hopefully it will soon be revised and can be merged

**Comment by flachica** [comment]
Hi @asierneiradev. To be merged this PR needs one more review. Please, click on `Files changed` and submit your review

imagen

**Review by asierneiradev — APPROVED** [review]

**Comment by john-herholz-dt** [comment]
Finally!

**Comment by rafaelbn** [comment]
Here you are @simahawk ! 😄 final review in order to get this merge! 👍

**Review by atchuthan — APPROVED** [review]

**Comment by simahawk** [comment]
> Dependency below, please review
> 
> [OCA/sale-workflow#2005](https://github.com/OCA/sale-workflow/pull/2005) [OCA/connector-prestashop#151](https://github.com/OCA/connector-prestashop/pull/151) [OCA/connector-ecommerce#70](https://github.com/OCA/connector-ecommerce/pull/70) [OCA/server-tools#2334](https://github.com/OCA/server-tools/pull/2334) [OCA/product-attribute#1070](https://github.com/OCA/product-attribute/pull/1070) [OCA/product-attribute#1069](https://github.com/OCA/product-attribute/pull/1069)

@flachica please do not mention all these PRs in all PRs as "dependencies".
They are "related" but they do not depend on each other.

If you do so, ppl will expect to review those PRs first to unlock this one. Or, like in my case, I will not merge at first because I'll see those pending links and I'll have to spend some time understanding that they are actually not blocking at all.
Please, clean them up or make these references more clear.

Thanks for your understanding!

**Comment by simahawk** [comment]
> @simahawk your merge command was aborted due to failed check(s), which you can inspect on [this commit of 15.0-ocabot-merge-pr-428-by-simahawk-bump-nobump](https://github.com/OCA/connector/commits/346e5344e2360e569a6c207ab174a1d4f4fa001d).
> 
> After fixing the problem, you can re-issue a merge command. Please refrain from merging manually as it will most probably make the target branch red.

we need this https://github.com/OCA/connector/pull/455

**Comment by simahawk** [comment]
Merged, can you rebase pls?

**Comment by flachica** [comment]
Thanks for your work @simahawk. Rebased

**Pull request merged**
