### PR TITLE
[10.0] Use more permissive license AGPL3 → LGPL3

### PR DESCRIPTION
**Pull request by bobslee**
This addresses #367, to follow [11.0], [12.0] and [13.0] similar license change.

### CODE REVIEW

**Review by guewen — APPROVED** [review]

**Comment by pedrobaeza** [comment]
This got stuck. You can relaunch again.

**Comment by pedrobaeza** [comment]
Let me try:

/ocabot merge minor

**Comment by pedrobaeza** [comment]
No way to make this work with the bot. Let's use the manual merge.

**Pull request merged**
