### PR TITLE
Default binder

### PR DESCRIPTION
**Pull request by ccomb**
Default Binder implementation to avoid rewriting it in each connector

### CODE REVIEW

**Comment by lmignon** [comment]
:+1: Nice idea  (Code review only)

**Comment by bguillot** [comment]
Very useful :+1:

**Comment by guewen** [comment]
Thanks @ccomb! I rebased and made small changes here: particularly one thing I want to change, here is my proposal #91

**Comment by guewen** [comment]
Closing as there is #91.

**Pull request closed without merging**
