### PR TITLE
Automatically build and push docs to GitHub Pages

### PR DESCRIPTION
**Pull request by guewen**
Use Travis to build the sphinx documentation at each new commit.

Once build, the doc is available at http://oca.github.io/connector
The goal being to redirect the domain odoo-connector.com on this URL once this PR is merged.

The docs are built in the `script` part, so if it fails, the build is considered failed.
The docs are then pushed in `after_success` so if it fails, the build remain green. It is only pushed when the branch is `8.0`.

As an example, you can see the result on my fork:
- the builds: https://travis-ci.org/guewen/connector/builds
- the gh-pages branch: https://github.com/guewen/connector/tree/gh-pages
- the served pages: http://guewen.github.io/connector/

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Very interesting! What is the objective of the secure part of the Travis file?

**Comment by guewen** [comment]
@pedrobaeza To achieve that, I had to create a new Token on my GitHub profile allowing Travis to push on my branch. The secure part contains my encrypted token and is available in the script in the `${GH_TOKEN}` environment variable (used in `git remote add upstream https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git`.

I should say that it is based on this article: http://hoverbear.org/2015/03/07/rust-travis-github-pages/

**Comment by yvaucher** [comment]
It works :+1:

**Comment by pedrobaeza** [comment]
Thanks for the vast info on the topic. @bwrsandman is going to be also interested, as he's is working now on the translation part.

For this PR, :+1:

**Comment by lmignon** [comment]
:+1:  One step further in the quality improvement process of community modules.

**Comment by jgrandguillaume** [comment]
Indeed that's a very interesting one ! :+1:

**Comment by guewen** [comment]
odoo-connector.com will be on sync once we have changed the CNAME target.

**Comment by guewen** [comment]
I realize that my token is valid for guewen/connector, not for OCA/connector.
I need someone having an access to the project settings to generate a new token.

See the section "Giving Travis Permissions" on this page: http://hoverbear.org/2015/03/07/rust-travis-github-pages
1. Create a new token on the OCA having only the "public_repo" scope
2. In the 8.0 branch of the `connector` project (if you don't have travis, `sudo gem install travis`), run:

```
travis encrypt GH_TOKEN=$THE_NEW_TOKEN
```
1. Copy the secured token output by `travis` in the `.travis.yml` file in the `env → secure` option.
2. Push, for such change, no need to make a PR I think.

@jgrandguillaume or @gurneyalex could you create this token please?

Edit: that's ok now.

**Comment by guewen** [comment]
Or maybe @sebastienbeau ?

Edit: that's ok now.

**Pull request merged**
