### PR TITLE
[15.0] component: fix mock import

### PR DESCRIPTION
**Pull request by sonhd91**

### CODE REVIEW

**Comment by guewen** [comment]
Hi @sonhd91 thanks for the fix!
You fixed the import correctly, however we should handle `sphinx_bootstrap_theme` differently IMO, I suggest to remove it from this PR and handle it in https://github.com/OCA/connector/pull/471#issuecomment-1785145561

**Comment by sonhd91** [comment]
> Hi @sonhd91 thanks for the fix! You fixed the import correctly, however we should handle `sphinx_bootstrap_theme` differently IMO, I suggest to remove it from this PR and handle it in [#471 (comment)](https://github.com/OCA/connector/pull/471#issuecomment-1785145561)

Okay, branch updated

**Review by guewen — APPROVED** [review]
Thanks!

**Pull request closed without merging**
