### PR TITLE
call super().unlink() after the binding has been deleted

### PR DESCRIPTION
**Pull request by damdam-s**
beenn deleted

### CODE REVIEW

**Review by Tonow-c2c — APPROVED** [review]
LGTM

**Review by leemannd — APPROVED** [review]

**Review by gurneyalex — COMMENTED** [review]
I'm pretty sure you still have a race condition here : the execution of the job is asynchronous I think, and can happen after the call to unlink? In that case you still have an error.

**Comment by guewen** [comment]
> I'm pretty sure you still have a race condition here : the execution of the job is asynchronous I think, and can happen after the call to unlink? In that case you still have an error.

At this point there is no job involved, this is the part handling the events propagation, which is all synchronous. The issue here is that when listeners of the event are triggered, the record has already been dropped, so they can't do anything with it.

It was correct in 9.0:

https://github.com/OCA/connector/blob/caee9b08818f550d18bf0193e21ae3abb3d3c632/connector/producer.py#L81-L89

And in 11.0 with the new events 

https://github.com/OCA/connector/blob/71b9d44f06658631367a8843144fdde6b77915ad/component_event/models/base.py#L106-L111

Regarding the jobs, as they are committed in the same transaction, they won't start before in any case.

**Review by guewen — APPROVED** [review]
Thanks!

**Review by lmignon — APPROVED** [review]

**Pull request merged**
