### PR TITLE
Fix Pylint warnings

### PR DESCRIPTION
**Pull request by guewen**
Supersedes #30

### CODE REVIEW

**Comment by guewen** [comment]
Hoping for the green

**Comment by lmignon** [comment]
:+1:  green! Thank you for this new cleaning.

**Comment by guewen** [comment]
I will just rebase to merge some commits

**Comment by lmignon** [comment]
fingers crossed it stays green

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Pull request merged**
