### PR TITLE
Adjusted Terms

### PR DESCRIPTION
**Pull request by rschnapka**
Job->Auftrag, Task->Aufgabe, Checkpoint->Kontrolle, OpenERP -> ODOO and a few other corrections to typos...

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Technically speaking is :+1:

**Comment by OSguard** [comment]
the connector translation we handle in launchpad in the past:
https://translations.launchpad.net/openerp-connector
so @guewen how we deal with this?

**Comment by guewen** [comment]
We have to deal with them manually until we have an integration with transifex (IIRC), so the PR is well and welcome. I just can't review the terms in themselves, but I bet you can @OSguard ;-)

**Comment by pedrobaeza** [comment]
PR for the translation bot is here for review: https://github.com/OCA/server-tools/pull/76. @max3903 is with it.

**Comment by guewen** [comment]
:+1:

**Pull request merged**
