### PR TITLE
add decorator to unlink

### PR DESCRIPTION
**Pull request by lepistone**
This is an alternative to pull request #32.

### CODE REVIEW

**Comment by guewen** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by guewen** [comment]
Oops, conflicting

**Comment by guewen** [comment]
@lepistone do you need this change? could you rebase and fix the conflict?

**Comment by lepistone** [comment]
This is WIP I made in a rush because I had the impression that #32 was giving other trouble I haven't investigated further. Then odoo experience came... Let's leave it as WIP, I'll report back here.

**Comment by lmignon** [comment]
@lepistone Is this PR still required?

**Comment by lepistone** [comment]
Thanks @lmignon: this can be closed.

**Pull request closed without merging**
