### PR TITLE
Activate transifex

### PR DESCRIPTION
**Pull request by guewen**

### CODE REVIEW

**Comment by max3903** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by guewen** [comment]
Merged too fast, build is failing. I'm investigating.

**Comment by yvaucher** [comment]
@guewen I think it's red because the branchwas deleted too fast

fatal: Couldn't find remote ref refs/pull/81/merge

**Comment by yvaucher** [comment]
Ok it failed on 2 jobs https://travis-ci.org/OCA/connector/builds/67032228

**Comment by guewen** [comment]
@yvaucher no I mean, the HEAD of 8.0 is red now. I corrected it in #82 (but still waiting for the green build to be sure it's corrected...)

**Pull request merged**
