### PR TITLE
[IMP] Add possibility to ignore backend

### PR DESCRIPTION
**Pull request by OpenCode**
An external software we use to connect to Odoo, create a new database every year. Every copy of database has the some information inside. If I create 2 backend for every database, the information (at first run of import) are duplicated because connector search information separated for backend id.

With this parameter, it's possibile to ignore backend.

### CODE REVIEW

**Comment by guewen** [comment]
Thanks for the proposal. It seems rather specific to your implementation, and I would suggest you to implement your own Binder in your connector.

**Comment by OpenCode** [comment]
I propose PR because I thing this implementation can be useful for others. In my situation I use functions of connector and I can't bypass this problem with my binder

**Comment by guewen** [comment]
> I propose PR because I thing this implementation can be useful for others. In my situation I use functions of connector and I can't bypass this problem with my binder

Why? I see no reason you couldn't do. Can you point me to some code so I can see what is blocking you?

**Comment by flotho** [comment]
Hi,
IMHO, working with a state on backend could be better. 
As an example, one of our customer changed its Prestashop recently and we had to face 2 simultaneous PS backend with huge quantity of job failed because we set an absurd location for preventing double synchro. We really would like to be able to deactivate backends and open new without problem.

@OpenCode don't you think active / state on Backend could solve your issue?

**Comment by guewen** [comment]
@flotho  I used a state in a custom implementation too. In the end, this should be handled in the implementations.

**Comment by OpenCode** [comment]
@flotho Set a state is not a solution for my situation because we have 2 (or more) backend active in the some moment

**Pull request closed without merging**
