### PR TITLE
[17.0][MIG] connector_base_product: Migration to 17.0

### PR DESCRIPTION
**Pull request by john-herholz-dt**
Simple migration.
- removed XML declaration from index.html as it is deprecated
- changed invisible="1" to invisible="True" to reflect View-Pocalypse

### CODE REVIEW

**Comment by john-herholz-dt** [comment]
This PR is still active and ready to get merged. Can someone review and merge it?
Thank you

**Review by dreispt — APPROVED** [review]

**Review by bizzappdev — APPROVED** [review]
LGTM

**Comment by john-herholz-dt** [comment]
@pedrobaeza Can you merge this, please?

**Comment by pedrobaeza** [comment]
Merging blindly due to reviews:

/ocabot migration connector_base_product
/ocabot merge nobump

**Comment by pedrobaeza** [comment]
@sbidoul I'm finding this error across all 17.0 repos:

```
psycopg2.errors.UndefinedObject: operator class "gin_trgm_ops" does not exist for access method "gin"
```

Do you know what it is?

**Comment by john-herholz-dt** [comment]
@pedrobaeza can you run the merge command again? The issue with gin should be resolved now.
Thank you!

**Pull request merged**
